storage_conn: "user=your_username password=your_password dbname=wb-order-service host=localhost port=5432 sslmode=disable"
http_server:
  address: "localhost:8090"
  timeout: 4s
  idle_timeout: 60s
nats_streaming:
  cluster_id: "test-cluster"
  client_id: "wb-order-service"
  subject: "wb-tech"
